<?php

	// ImageSlider - (c) Copyright 2008-2017 by Hetfield - www.MerZ-IT-SerVice.de
	// only original from https://www.merz-it-service.de/Installation-ImageSlider-v1-5::74.html

	define('MODULE_MITS_IMAGESLIDER_TEXT_TITLE', 'ImageSlider v2.02 &copy; by Hetfield (MerZ IT-SerVice)');
	define('MODULE_MITS_IMAGESLIDER_TEXT_DESCRIPTION', '<a href="https://www.merz-it-service.de/" target="_blank"><img src="'.DIR_WS_EXTERNAL.'mits_imageslider/images/merz-it-service.png" border="0" alt="" style="display:block;max-width:100%;height:auto;" /></a><br />Mit dem ImageSlider-Modul k&ouml;nnen Sie eine Bilderslideshow auf der Startseite Ihres Shops erstellen. Sie k&ouml;nnen dort wechselnde Bilder mit Kategorien, Produkten, Content oder anderen Shopseiten ohne Sessionverlust verlinken oder zu einer externen Adresse verlinken.<br/><br/>Das bereits mehrere tausendfach bew&auml;hrte ImageSlider-Modul &copy by Hetfield erhalten Sie im Original nur vom Hersteller unter <a target="_blank" href="https://www.merz-it-service.de/Installation-ImageSlider-v1-5::74.html"><strong><u>MerZ IT-SerVice</u></strong></a> f&uuml;r Ihre modified eCommerce Shopsoftware.<br /><br /><a href="http://imageslider.merz-it-service.de/readme.html" target="_blank" onclick="window.open(\'http://imageslider.merz-it-service.de/readme.html\', \'Anleitung f&uuml;r das Modul ImageSlider v2.02\', \'scrollbars=yes,resizable=yes,menubar=yes,width=960,height=600\'); return false"><strong><u>Anleitung f&uuml;r das Modul ImageSlider v2.02</u></strong></a>');
	define('MODULE_MITS_IMAGESLIDER_STATUS_TITLE', 'ImageSlider-Modul aktivieren?');
	define('MODULE_MITS_IMAGESLIDER_STATUS_DESC', 'Das Modul ImageSlider v2.02 aktivieren');
	define('MODULE_MITS_IMAGESLIDER_SHOW_TITLE', 'Anzeige des Imagslider');
	define('MODULE_MITS_IMAGESLIDER_SHOW_DESC', 'Wo soll der ImageSlider angezeigt werden, bzw. verf&uuml;gbar sein? <br /><ul><li>start = nur auf der Startseite (default)</li><li>general = Anzeige auf allen Seiten (notwenig bei der Nutzung des ImageSliders &uuml;ber Smarty-Plugin mit <br /><i>{getImageSlider slidergroup=mits_imageslider}</i> <br />in anderen Templatedateien ausser der index.html)</li></ul>');
	define('MODULE_MITS_IMAGESLIDER_TYPE_TITLE', 'Slider-Plugin ausw&auml;hlen');
	define('MODULE_MITS_IMAGESLIDER_TYPE_DESC', 'Hinweis: Alle Plugins setzen eine vorhandene jQuery-Bibliothek voraus. Sollte das im Shop verwendete Template diese Voraussetzung nicht erf&uuml;llen, binden Sie diese bitte vor der Aktivierung des Modul in Ihr Template ein. Au&szlig;erdem achten Sie darauf, dass ihr gew&auml;hltes Plugin nicht schon bereits im Template vorhanden ist (z.B. das bxSlider-Plugin im Standard-Template tpl_modified).');
	define('MODULE_MITS_IMAGESLIDER_LOADJAVASCRIPT_TITLE', 'JavaScript-Files vom Slider-Plugin laden?');
	define('MODULE_MITS_IMAGESLIDER_LOADJAVASCRIPT_DESC', 'Das Modul ImageSlider verwendet bei der Einstellung "true" die Javascript-Dateien vom ImageSlider-Modul. Bei der Einstellung "alse" werden die Javascript-Dateien nicht geladen. Die Einstellung "false" ist eigentlich nur dann notwendig, wenn das gew&uuml;nschte Slider-Plugin bereits durch andere Anpassungen im Shop verf&uuml;gbar ist (z.B. durch manuelle Installation im Template o.&auml;). Bei der Einstellung "false" wird nur die Datei <i>mits_imageslider.js</i> im jeweiligen Plugin-Ordner (<i>includes/external/mits_imageslider/plugins/PLUGINNAME/</i>) geladen.');
	define('MODULE_MITS_IMAGESLIDER_LOADCSS_TITLE', 'CSS-Files vom Slider-Plugin laden?');
	define('MODULE_MITS_IMAGESLIDER_LOADCSS_DESC', 'Das Modul ImageSlider verwendet bei der Einstellung "true" die CSS-Dateien vom ImageSlider-Modul. Bei der Einstellung "false" werden die CSS-Dateien nicht geladen. Die Einstellung "false" ist eigentlich nur dann notwendig, wenn das gew&uuml;nschte Slider-Plugin bereits durch andere Anpassungen im Shop verf&uuml;gbar ist (z.B. durch manuelle Installation/Anpassungen im Template o.&auml;).');
	define('MAX_DISPLAY_IMAGESLIDERS_RESULTS_TITLE', 'Anzeige ImageSlider-Eintr&auml;ge pro Seite in der Administration');
	define('MAX_DISPLAY_IMAGESLIDERS_RESULTS_DESC', 'Wieviel ImageSlider-Eintr&auml;ge sollen pro Seite im Administrationsbereich des Shops angezeigt werden? Die Einstellung kann auch direkt in der &Uuml;bersicht ge&auml;ndert werden.');
?>